comment: false
language: R
sudo: false
cache: packages
after_success:
- Rscript -e 'covr::codecov()'

codecov:
  token: ac9ec8da-cbdd-490a-b90e-fdfc5eabe41d

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true


